# Generated by Django 5.1.2 on 2024-10-22 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField()),
                ('source', models.CharField(max_length=50)),
                ('bank', models.CharField(max_length=100)),
                ('title', models.TextField()),
                ('review_text', models.TextField()),
                ('rating', models.FloatField(blank=True, null=True)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('url', models.URLField(blank=True, max_length=500, null=True)),
                ('source_type', models.CharField(blank=True, max_length=50, null=True)),
                ('review_sentiment', models.CharField(max_length=50)),
                ('sentiment_score', models.IntegerField()),
            ],
        ),
    ]
